packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  credentials_file        = "/Users/amreshrajvindersingh/Documents/Applications/Keys/devv-414701-3253003787e9.json"
  disk_size           = 100
  image_name          = "custom-image-${local.timestamp}"
  project_id          = "devv-414701"
  source_image_family = "centos-stream-8"
  ssh_username        = "dev"
  zone                = "us-central1-a"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/webapp.zip"
    source      = "/Users/amreshrajvindersingh/Documents/webapp.zip"
  }

  provisioner "file" {
    destination = "/tmp/star.service"
    source      = "star.service"
  }

  provisioner "shell" {
    script = "dependencies.sh"
  }

  provisioner "shell" {
    script = "owner.sh"
  }

}
