variable "credentials_file" {
  type    = string
}

variable "disk_size" {
  type    = number
}

variable "image_name" {
  type    = string
}

variable "project_id" {
  type    = string
}

variable "source_image_family" {
  type    = string
}

variable "ssh_username" {
  type    = string
}

variable "zone" {
  type    = string
}

variable "webapp_source" {
  type    = string
}

variable "webapp_destination" {
  type    = string
}

variable "star_service_source" {
  type    = string
}

variable "star_service_destination" {
  type    = string
}

variable "dependencies_script" {
  type    = string
}

variable "owner_script" {
  type    = string
}
variable "amresh_devkey" {
  type = string
}

packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
}

source "googlecompute" "autogenerated_1" {
  credentials_json    =var.amresh_devkey
  disk_size           = var.disk_size
  image_name          = var.image_name
  project_id          = var.project_id
  source_image_family = var.source_image_family
  ssh_username        = var.ssh_username
  zone                = var.zone
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "file" {
    destination = var.webapp_destination
    source      = var.webapp_source
  }

  provisioner "file" {
    destination = var.star_service_destination
    source      = var.star_service_source
  }

  provisioner "shell" {
    script = var.dependencies_script
  }

  provisioner "shell" {
    script = var.owner_script
  }
}
